// ============================================================
// Question bank. Each question is a sliding scale between two
// extremes. left = slider at 0, right = slider at 1.
// Add your own! The game never repeats a question in one session.
// ============================================================

export const QUESTIONS = [
  { q: "How scared of heights are they?", left: "Not scared at all", right: "Absolutely terrified" },
  { q: "Could they survive a week in the wilderness?", left: "Gone in a day", right: "Basically a survivalist" },
  { q: "How often do they get lost?", left: "Human GPS", right: "Lost in their own house" },
  { q: "How spicy do they like their food?", left: "Ketchup is spicy", right: "Ghost pepper, please" },
  { q: "How are they before their morning coffee/tea?", left: "Perfectly pleasant", right: "Do not approach" },
  { q: "How likely are they to cry at a movie?", left: "Heart of stone", right: "Sobbing at trailers" },
  { q: "How competitive are they at board games?", left: "Just here for fun", right: "Flips the table" },
  { q: "How messy is their room right now?", left: "Museum clean", right: "Biohazard zone" },
  { q: "How good are they at keeping secrets?", left: "The vault", right: "Tells everyone instantly" },
  { q: "How long could they go without their phone?", left: "Weeks, easily", right: "Ten minutes, max" },
  { q: "How likely are they to talk to strangers?", left: "Avoids all eye contact", right: "Befriends the whole bus" },
  { q: "How brave are they with scary movies?", left: "Hides behind a pillow", right: "Laughs at jump scares" },
  { q: "How good a dancer do they think they are?", left: "Two left feet", right: "Born to perform" },
  { q: "How likely are they to be late?", left: "Always 15 minutes early", right: "Late to everything" },
  { q: "How much do they love karaoke?", left: "Would rather disappear", right: "Grabs the mic first" },
  { q: "How picky an eater are they?", left: "Eats anything", right: "Extremely picky" },
  { q: "How likely are they to win a trivia night?", left: "First one out", right: "Carries the team" },
  { q: "How often do they laugh at their own jokes?", left: "Never", right: "Before the punchline" },
  { q: "How well would they do in a zombie apocalypse?", left: "First to go", right: "Leads the survivors" },
  { q: "How much of a morning person are they?", left: "Nocturnal creature", right: "Up at 5am, thriving" },
  { q: "How dramatic are they when they get a small cold?", left: "Doesn't even mention it", right: "Writes their will" },
  { q: "How likely are they to return a library book on time?", left: "Owes hundreds in fees", right: "Never late once" },
  { q: "How good are they with plants?", left: "Kills a cactus", right: "Full jungle at home" },
  { q: "How likely are they to eat dessert before dinner?", left: "Never, rules are rules", right: "Dessert IS dinner" },
  { q: "How patient are they in a long line?", left: "Zen master", right: "Visibly vibrating" },
  { q: "How likely are they to sing in the shower?", left: "Silent as a monk", right: "Full concert, encores" },
  { q: "How good are they at parallel parking?", left: "Drives away instead", right: "First try, every time" },
  { q: "How much do they overpack for trips?", left: "One tiny backpack", right: "Three suitcases for a weekend" },
  { q: "How likely are they to believe in ghosts?", left: "Total skeptic", right: "Has met several" },
  { q: "How likely are they to snooze their alarm?", left: "Up on the first ring", right: "Snoozes into next week" },
  { q: "How chatty are they at 7am?", left: "Grunts only", right: "Full podcast mode" },
  { q: "How well do they handle being hangry?", left: "Totally fine", right: "A danger to society" },
  { q: "How likely are they to cheat at Monopoly?", left: "Painfully honest", right: "Sleeves full of cash" },
  { q: "How good is their poker face?", left: "Face says everything", right: "Unreadable statue" },
  { q: "How likely are they to adopt a stray animal on sight?", left: "Keeps walking", right: "Already named it" },
  { q: "How much do they enjoy public speaking?", left: "Worst nightmare", right: "Lives for the spotlight" },
  { q: "How likely are they to finish a book they started?", left: "Abandons every book", right: "Finishes even the bad ones" },
  { q: "How adventurous are they with new food?", left: "Sticks to the usual", right: "Orders the mystery dish" },
  { q: "How likely are they to remember your birthday?", left: "Forgets their own", right: "Remembers everyone's" },
  { q: "How much do they gesture when they talk?", left: "Hands in pockets", right: "Air traffic controller" },
  { q: "How likely are they to start a workout plan Monday?", left: "Never claimed they would", right: "Every single Monday" },
  { q: "How good are they at whispering?", left: "Actually quiet", right: "Whisper heard across the room" },
];
