// ============================================================
// Question bank. Each question is a sliding scale between two
// extremes. left = slider at 0, right = slider at 1.
// Add your own! The game never repeats a question in one session.
// ============================================================

export const QUESTIONS = [
  { q: "How scared of heights are they?", left: "Not scared at all", right: "Absolutely terrified" },
  { q: "Could they survive a week in the wilderness?", left: "Gone in a day", right: "Basically a survivalist" },
  { q: "How often do they get lost?", left: "Human GPS", right: "Lost in their own house" },
  { q: "How spicy do they like their food?", left: "Ketchup is spicy", right: "Ghost pepper, please" },
  { q: "How are they before their morning coffee/tea?", left: "Perfectly pleasant", right: "Do not approach" },
  { q: "How likely are they to cry at a movie?", left: "Heart of stone", right: "Sobbing at trailers" },
  { q: "How competitive are they at board games?", left: "Just here for fun", right: "Flips the table" },
  { q: "How messy is their room right now?", left: "Museum clean", right: "Biohazard zone" },
  { q: "How good are they at keeping secrets?", left: "The vault", right: "Tells everyone instantly" },
  { q: "How long could they go without their phone?", left: "Weeks, easily", right: "Ten minutes, max" },
  { q: "How likely are they to talk to strangers?", left: "Avoids all eye contact", right: "Befriends the whole bus" },
  { q: "How brave are they with scary movies?", left: "Hides behind a pillow", right: "Laughs at jump scares" },
  { q: "How good a dancer do they think they are?", left: "Two left feet", right: "Born to perform" },
  { q: "How likely are they to be late?", left: "Always 15 minutes early", right: "Late to everything" },
  { q: "How much do they love karaoke?", left: "Would rather disappear", right: "Grabs the mic first" },
  { q: "How picky an eater are they?", left: "Eats anything", right: "Extremely picky" },
  { q: "How likely are they to win a trivia night?", left: "First one out", right: "Carries the team" },
  { q: "How often do they laugh at their own jokes?", left: "Never", right: "Before the punchline" },
  { q: "How well would they do in a zombie apocalypse?", left: "First to go", right: "Leads the survivors" },
  { q: "How much of a morning person are they?", left: "Nocturnal creature", right: "Up at 5am, thriving" },
  { q: "How dramatic are they when they get a small cold?", left: "Doesn't even mention it", right: "Writes their will" },
  { q: "How likely are they to return a library book on time?", left: "Owes hundreds in fees", right: "Never late once" },
  { q: "How good are they with plants?", left: "Kills a cactus", right: "Full jungle at home" },
  { q: "How likely are they to eat dessert before dinner?", left: "Never, rules are rules", right: "Dessert IS dinner" },
  { q: "How patient are they in a long line?", left: "Zen master", right: "Visibly vibrating" },
  { q: "How likely are they to sing in the shower?", left: "Silent as a monk", right: "Full concert, encores" },
  { q: "How good are they at parallel parking?", left: "Drives away instead", right: "First try, every time" },
  { q: "How much do they overpack for trips?", left: "One tiny backpack", right: "Three suitcases for a weekend" },
  { q: "How likely are they to believe in ghosts?", left: "Total skeptic", right: "Has met several" },
  { q: "How likely are they to snooze their alarm?", left: "Up on the first ring", right: "Snoozes into next week" },
  { q: "How chatty are they at 7am?", left: "Grunts only", right: "Full podcast mode" },
  { q: "How well do they handle being hangry?", left: "Totally fine", right: "A danger to society" },
  { q: "How likely are they to cheat at Monopoly?", left: "Painfully honest", right: "Sleeves full of cash" },
  { q: "How good is their poker face?", left: "Face says everything", right: "Unreadable statue" },
  { q: "How likely are they to adopt a stray animal on sight?", left: "Keeps walking", right: "Already named it" },
  { q: "How much do they enjoy public speaking?", left: "Worst nightmare", right: "Lives for the spotlight" },
  { q: "How likely are they to finish a book they started?", left: "Abandons every book", right: "Finishes even the bad ones" },
  { q: "How adventurous are they with new food?", left: "Sticks to the usual", right: "Orders the mystery dish" },
  { q: "How likely are they to remember your birthday?", left: "Forgets their own", right: "Remembers everyone's" },
  { q: "How much do they gesture when they talk?", left: "Hands in pockets", right: "Air traffic controller" },
  { q: "How likely are they to start a workout plan Monday?", left: "Never claimed they would", right: "Every single Monday" },
  { q: "How good are they at whispering?", left: "Actually quiet", right: "Whisper heard across the room" },

  { q: "How big is their sweet tooth?", left: "Meh, sugar", right: "Dessert with every meal" },
  { q: "How likely are they to dance at a wedding?", left: "Glued to the chair", right: "First on the floor" },
  { q: "How scared of spiders are they?", left: "Picks them up bare-handed", right: "Burns the house down" },
  { q: "How scared of the dark are they?", left: "Not even a little", right: "Sleeps with 3 lights on" },
  { q: "How good a cook are they?", left: "Burns water", right: "Restaurant quality" },
  { q: "How neat is their handwriting?", left: "Doctor's scribbles", right: "Basically a font" },
  { q: "How good are they at remembering names?", left: "Forgets instantly", right: "Never forgets one" },
  { q: "How often do they lose their keys?", left: "Never, ever", right: "Currently lost right now" },
  { q: "How stubborn are they?", left: "Totally flexible", right: "Immovable object" },
  { q: "How ticklish are they?", left: "Not at all", right: "Can't even be poked" },
  { q: "How likely are they to laugh at the worst possible moment?", left: "Always composed", right: "Giggles at funerals" },
  { q: "How likely are they to talk to animals like people?", left: "Never", right: "Full conversations daily" },
  { q: "How good are they at video games?", left: "Controller held upside down", right: "Basically a pro" },
  { q: "How likely are they to cry from laughing?", left: "Never happens", right: "Weekly occurrence" },
  { q: "How likely are they to fall asleep during a movie?", left: "Wide awake to the credits", right: "Gone in 10 minutes" },
  { q: "How loud is their sneeze?", left: "Silent little squeak", right: "Scares the neighbors" },
  { q: "How good are they at wrapping presents?", left: "Tape and prayers", right: "Department store perfect" },
  { q: "How likely are they to rewatch the same show over and over?", left: "Always something new", right: "Same show, 12th time" },
  { q: "How likely are they to eat the last slice without asking?", left: "Would never", right: "Already ate it" },
  { q: "How good are they at math without a calculator?", left: "Fingers and toes", right: "Human calculator" },
  { q: "How scared of needles are they?", left: "Doesn't even flinch", right: "Faints in the parking lot" },
  { q: "How much do they love rollercoasters?", left: "Absolutely not", right: "Front row, hands up" },
  { q: "How likely are they to jump into a freezing lake?", left: "Never in a million years", right: "Already mid-air" },
  { q: "How good are they at telling jokes?", left: "Ruins every punchline", right: "Comedy special ready" },
  { q: "How likely are they to forget where they parked?", left: "Photographic memory", right: "Wanders the lot for hours" },
  { q: "How good are they at spelling?", left: "Spellcheck's biggest fan", right: "Spelling bee champion" },
  { q: "How do they feel about pineapple on pizza?", left: "It's a crime", right: "It's delicious" },
  { q: "How likely are they to become famous?", left: "Happily anonymous", right: "Destined for stardom" },
  { q: "How likely are they to talk in their sleep?", left: "Silent all night", right: "Full speeches at 3am" },
  { q: "How long are their showers?", left: "In and out in 3 minutes", right: "Uses all the hot water" },
  { q: "How likely are they to order the same thing every time?", left: "Always something new", right: "The usual, please" },
  { q: "How good are they at charades?", left: "Painful to watch", right: "Guesses it in seconds" },
  { q: "How likely are they to trip over nothing?", left: "Graceful as a cat", right: "The floor attacked" },
  { q: "How good are they at doing accents?", left: "Everything sounds the same", right: "Could fool a local" },
  { q: "How likely are they to win a staring contest?", left: "Blinks immediately", right: "Eyes of stone" },
  { q: "How likely are they to eat breakfast food for dinner?", left: "Breakfast is for mornings", right: "Pancakes at midnight" },
  { q: "How scared of clowns are they?", left: "Clowns are fine", right: "Absolutely terrified" },
  { q: "How likely are they to make a wish at 11:11?", left: "Never noticed", right: "Sets an alarm for it" },
  { q: "How good are they at saving money?", left: "Money burns a hole", right: "Squirrel with a budget" },
  { q: "How likely are they to impulse buy something silly?", left: "Every purchase is planned", right: "Cart's already full" },
  { q: "How loud is their laugh?", left: "Silent shoulder shakes", right: "Heard from the street" },
  { q: "How likely are they to fall for a prank?", left: "Sees it coming a mile away", right: "Falls for it every time" },
  { q: "How good are they at drawing?", left: "Stick figures at best", right: "Gallery worthy" },
  { q: "How likely are they to nap on a weekend?", left: "Naps are for babies", right: "It's on the schedule" },
  { q: "How many alarms do they set?", left: "Just one", right: "Seventeen, five minutes apart" },
  { q: "How likely are they to sing along to commercials?", left: "Never", right: "Knows every jingle" },
  { q: "How good are they at remembering movie quotes?", left: "Draws a blank", right: "Recites whole scenes" },
  { q: "How likely are they to apologize to furniture after bumping it?", left: "It's just a table", right: "Sorry, Mr. Chair" },
  { q: "How organized is their bag or backpack?", left: "A black hole", right: "Everything has a pocket" },
  { q: "How fast do they walk?", left: "Leisurely stroll", right: "Olympic speedwalker" },
  { q: "How good are they at hide and seek?", left: "Found in 5 seconds", right: "Still hiding since 2019" },
  { q: "How likely are they to win an eating contest?", left: "Full after 3 bites", right: "Undefeated champion" },
  { q: "How likely are they to check the fridge again hoping new food appeared?", left: "Once is enough", right: "Every 10 minutes" },
  { q: "How likely are they to say 'you too' when a waiter says 'enjoy your meal'?", left: "Never slips up", right: "Every single time" },
  { q: "How nervous do they get before a big test or interview?", left: "Cool as a cucumber", right: "Full panic mode" },
  { q: "How good are they at rock paper scissors?", left: "Loses every time", right: "Unbeatable strategist" },
  { q: "How good are they at remembering song lyrics?", left: "Mumbles everything", right: "Human jukebox" },
  { q: "How likely are they to become a millionaire?", left: "Not the goal", right: "Just a matter of time" },
  { q: "How much do they like surprises?", left: "Tell me everything now", right: "Surprise me always" },
  { q: "How much do they laugh at dad jokes?", left: "Eye roll only", right: "Tears of joy" },
  { q: "How good are they with little kids?", left: "Kids sense fear", right: "Instant best friend" },
  { q: "How likely are they to keep a New Year's resolution?", left: "Broken by January 2nd", right: "Sticks it out all year" },
  { q: "How fast do they text?", left: "One finger, slowly", right: "Thumbs are a blur" },
  { q: "How likely are they to eat raw cookie dough?", left: "Follows the warning label", right: "The cookies never get baked" },
  { q: "How much do they like camping?", left: "Room service only", right: "Give me a tent and a fire" },
  { q: "How likely are they to pet every dog they see?", left: "Walks right past", right: "Crosses the street for it" },
  { q: "How much do they love gossip?", left: "Not interested", right: "Tell me EVERYTHING" },
  { q: "How patient are they helping someone with technology?", left: "Gives up instantly", right: "Saint-level patience" },
  { q: "How likely are they to volunteer to go first?", left: "Hides in the back", right: "Hand's already up" },
  { q: "How much do they procrastinate?", left: "Done weeks early", right: "Started at 11:59pm" },
  { q: "How likely are they to read instructions before building furniture?", left: "Instructions are a suggestion", right: "Reads every word twice" },
  { q: "How likely are they to cry at a wedding?", left: "Dry eyes all day", right: "Sobbing at the vows" },
  { q: "How likely are they to get a tattoo?", left: "Never ever", right: "Already planning the next one" },
  { q: "How much do they love winter?", left: "Hibernates until spring", right: "More snow, please" },
  { q: "How many browser tabs do they have open?", left: "Just one, always", right: "Seventy-three and counting" },
  { q: "How likely are they to start a food fight?", left: "Food is sacred", right: "First pie's already flying" },
];
